package(default_visibility=["//visibility:public"])
load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
    name = "grid_row",
    srcs = ["grid_row.ts"],
    deps = ["//src/avatar_cell"],
)