package(default_visibility=["//visibility:public"])
load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
    name = "avatar_cell",
    srcs = ["avatar_cell.ts"],
    deps = ["//src/avatar"],
)